# NumPy Operations

## Arithmetic

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr/arr

C:\Users\MYLENO~1\AppData\Local\Temp/ipykernel_7408/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
1/0

ZeroDivisionError: division by zero

In [11]:
1/arr

C:\Users\MYLENO~1\AppData\Local\Temp/ipykernel_7408/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [16]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [17]:
np.log(arr)

C:\Users\MYLENO~1\AppData\Local\Temp/ipykernel_7408/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Statistical Functions

In [18]:
arr = np.arange(0,10)

In [19]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr.sum()

45

In [21]:
arr.mean()

4.5

In [22]:
arr.min()

0

In [23]:
arr.max()

9

In [24]:
arr.var()

8.25

In [25]:
arr.std()

2.8722813232690143

## Axis Logic
### axis = 0 Rows
### axis = 1 Cols

In [26]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [27]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr2d.shape

(3, 4)

In [29]:
arr2d.sum()

78

In [30]:
arr2d.sum(axis=0)

array([15, 18, 21, 24])

In [31]:
arr2d.sum(axis=1)

array([10, 26, 42])