# Numpy Indexing and Selection

In [28]:
import numpy as np

In [29]:
arr = np.arange(0,11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[9]

9

In [32]:
arr[0]

0

In [33]:
arr = np.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[9]

10

In [36]:
arr[5]

6

In [37]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [39]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [40]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [41]:
arr[6:]

array([ 7,  8,  9, 10])

In [42]:
arr[-1]

10

In [43]:
arr[1:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[0] = 50

In [46]:
arr

array([50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[0:6] = 50

In [48]:
arr

array([50, 50, 50, 50, 50, 50,  7,  8,  9, 10])

In [49]:
arr

array([50, 50, 50, 50, 50, 50,  7,  8,  9, 10])

In [50]:
arr = np.arange(1,11)

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
arr1 = arr.copy()

In [53]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr1[0:7] = 90

In [55]:
arr1

array([90, 90, 90, 90, 90, 90, 90,  8,  9, 10])

In [56]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Numpy 2D Array Indexing and Selection

In [57]:
arr2d = np.array(([1,10,100],[2,20,200],[3,30,300]))

In [58]:
arr2d

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300]])

In [59]:
arr2d[1]

array([  2,  20, 200])

In [60]:
arr2d[1][1]

20

In [61]:
arr2d[1:,1:]

array([[ 20, 200],
       [ 30, 300]])

In [62]:
arr2d[:2]

array([[  1,  10, 100],
       [  2,  20, 200]])

In [63]:
arr2d[2,:]

array([  3,  30, 300])

# Conditional Selection

In [64]:
arr = np.arange(1,11)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [67]:
boolarr = arr > 5

In [68]:
boolarr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [69]:
arr[boolarr]

array([ 6,  7,  8,  9, 10])

In [70]:
arr[arr>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [71]:
x = 3
arr[arr>x]

array([ 4,  5,  6,  7,  8,  9, 10])