# Numpy PART-3
### Array Attributes and Methods
## Reshape

In [1]:
import numpy as np

In [2]:
arr = np.arange(25)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
arr1 = np.random.randint(0,50,10)

In [6]:
arr1

array([42, 12, 38,  4, 26, 19, 41, 28, 29, 34])

In [7]:
arr1.max()

42

In [8]:
arr1.min()

4

In [9]:
arr1.argmin()

3

In [10]:
arr1.argmax()

0

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
arr.shape

(25,)

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
arr.reshape(5,5).shape

(5, 5)

In [17]:
arr.reshape(1,25)
arr.reshape(1,25).shape

(1, 25)

In [16]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

## dtype

In [18]:
arr.dtype

dtype('int32')

In [20]:
arr2 = np.array([1.5,2.5,3.5])

In [21]:
arr2.dtype

dtype('float64')