# Numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.22.2'

In [4]:
l1 = [10,20,30]

In [5]:
type(l1)

list

In [7]:
a1 = np.array([10,20,30])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2 = [10,20,30]

In [10]:
a1 = np.array(a2)

In [11]:
a1

array([10, 20, 30])

In [12]:
arr1 = [[10,20,30],[40,50,60],[70,80,90]]

In [13]:
arr1

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [14]:
np.array(arr1)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Linspace

In [23]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Numpy PART-2

## Random

In [26]:
import numpy as np

In [33]:
np.random.rand(5)

array([0.55428859, 0.35503633, 0.89048536, 0.2122195 , 0.03113368])

In [42]:
np.random.rand(5,5)

array([[0.48764428, 0.53142322, 0.75962221, 0.61546528, 0.95777987],
       [0.51257396, 0.81069764, 0.86364072, 0.58389313, 0.5803088 ],
       [0.13359112, 0.31687709, 0.45954168, 0.31661786, 0.18783262],
       [0.83244361, 0.49696036, 0.87464081, 0.65181594, 0.40264055],
       [0.3231613 , 0.24565383, 0.66627945, 0.7275719 , 0.88543535]])

In [50]:
np.random.randn(3)

array([ 1.86250547, -0.07928035,  2.04792857])

In [51]:
np.random.randn(5,5)

array([[-2.1406338 ,  1.1466659 , -0.37542857, -0.47732437, -1.48166701],
       [ 2.30637124,  1.01073758, -0.35710286,  0.56808957, -0.77140729],
       [-0.84979317,  0.32181568,  0.5209744 , -0.55168114,  0.5342262 ],
       [ 0.35328651, -0.75572807, -1.96173835, -0.84114328,  1.058055  ],
       [ 0.45876379, -1.09383929, -0.87142995, -0.01747565, -1.24021156]])

In [64]:
np.random.randint(1,100)

14

In [69]:
np.random.randint(1,100,15)

array([47, 27, 88, 42, 39, 39, 33, 54, 26, 31, 51, 88, 59,  4, 72])

In [71]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [72]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [75]:
np.random.seed(101)
np.random.randint(1,100,10)

array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41])

In [76]:
np.random.seed(101)
np.random.randint(1,100,10)

array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41])